


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from form1_widget import Ui_Form as form1_widget
from form2_widget import Ui_Form as form2_widget
from PyQt5.QtWidgets import QFileDialog 
from dashboard_widget import Ui_Form as DashBoard



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1221, 555)
        MainWindow.setMinimumSize(QtCore.QSize(10, 10))
        self.Most_outer_hcont = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Most_outer_hcont.sizePolicy().hasHeightForWidth())
        self.Most_outer_hcont.setSizePolicy(sizePolicy)
        self.Most_outer_hcont.setObjectName("Most_outer_hcont")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Most_outer_hcont)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header_Vcont = QtWidgets.QHBoxLayout()
        self.Header_Vcont.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.Header_Vcont.setSpacing(10)
        self.Header_Vcont.setObjectName("Header_Vcont")
        self.head_logo = QtWidgets.QLabel(self.Most_outer_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head_logo.sizePolicy().hasHeightForWidth())
        self.head_logo.setSizePolicy(sizePolicy)
        self.head_logo.setMinimumSize(QtCore.QSize(10, 10))
        self.head_logo.setMaximumSize(QtCore.QSize(50, 50))
        self.head_logo.setText("")
        self.head_logo.setPixmap(QtGui.QPixmap("icons/apshah_logo.png"))
        self.head_logo.setScaledContents(True)
        self.head_logo.setObjectName("head_logo")
        self.Header_Vcont.addWidget(self.head_logo)
        self.header_title = QtWidgets.QLabel(self.Most_outer_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_title.sizePolicy().hasHeightForWidth())
        self.header_title.setSizePolicy(sizePolicy)
        self.header_title.setMinimumSize(QtCore.QSize(10, 10))
        self.header_title.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.header_title.setStyleSheet("*{\n"
"    \n"
"    font: 75 15pt \"DejaVu Serif\";\n"
"}\n"
"")
        self.header_title.setObjectName("header_title")
        self.Header_Vcont.addWidget(self.header_title)
        self.head_btn = QtWidgets.QLabel(self.Most_outer_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head_btn.sizePolicy().hasHeightForWidth())
        self.head_btn.setSizePolicy(sizePolicy)
        self.head_btn.setMinimumSize(QtCore.QSize(10, 0))
        self.head_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.head_btn.setStyleSheet("")
        self.head_btn.setObjectName("head_btn")
        self.Header_Vcont.addWidget(self.head_btn)
        self.head_logout = QtWidgets.QLabel(self.Most_outer_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head_logout.sizePolicy().hasHeightForWidth())
        self.head_logout.setSizePolicy(sizePolicy)
        self.head_logout.setMinimumSize(QtCore.QSize(10, 0))
        self.head_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.head_logout.setObjectName("head_logout")
        self.Header_Vcont.addWidget(self.head_logout)
        self.head_drop = QtWidgets.QComboBox(self.Most_outer_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head_drop.sizePolicy().hasHeightForWidth())
        self.head_drop.setSizePolicy(sizePolicy)
        self.head_drop.setMinimumSize(QtCore.QSize(10, 0))
        self.head_drop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.head_drop.setCurrentText("")
        self.head_drop.setFrame(True)
        self.head_drop.setObjectName("head_drop")
        self.head_drop.addItem("")
        self.head_drop.addItem("")
        self.head_drop.addItem("")
        self.head_drop.addItem("")
        self.head_drop.addItem("")
        self.head_drop.addItem("")
        self.head_drop.setItemText(5, "")
        self.Header_Vcont.addWidget(self.head_drop)
        self.verticalLayout.addLayout(self.Header_Vcont)
        self.head_line = QtWidgets.QFrame(self.Most_outer_hcont)
        self.head_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.head_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.head_line.setObjectName("head_line")
        self.verticalLayout.addWidget(self.head_line)
        self.main_vcont = QtWidgets.QWidget(self.Most_outer_hcont)
        self.main_vcont.setObjectName("main_vcont")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_vcont)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_left_hcont = QtWidgets.QWidget(self.main_vcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_left_hcont.sizePolicy().hasHeightForWidth())
        self.main_left_hcont.setSizePolicy(sizePolicy)
        self.main_left_hcont.setMinimumSize(QtCore.QSize(80, 0))
        self.main_left_hcont.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.main_left_hcont.setStyleSheet("QPushButton{\n"
"    text-align: left;\n"
"    font: 75 italic 10pt \"DejaVu Serif\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-weight: bold\n"
"    \n"
"}\n"
"\n"
"QPushButton{\n"
"\n"
"height:30px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"\n"
"*{\n"
"margin-left: 15pt;\n"
"margin-right: 15pt;\n"
"min-width: 80px\n"
"}")
        self.main_left_hcont.setObjectName("main_left_hcont")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_left_hcont)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.menu_hcont = QtWidgets.QWidget(self.main_left_hcont)
        self.menu_hcont.setMinimumSize(QtCore.QSize(80, 0))
        self.menu_hcont.setStyleSheet("")
        self.menu_hcont.setObjectName("menu_hcont")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.menu_hcont)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.system_label = QtWidgets.QLabel(self.menu_hcont)
        self.system_label.setObjectName("system_label")
        self.verticalLayout_5.addWidget(self.system_label)
        self.Dashboard_btn = QtWidgets.QPushButton(self.menu_hcont)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Dashboard_btn.setIcon(icon)
        self.Dashboard_btn.setFlat(True)
        self.Dashboard_btn.setObjectName("Dashboard_btn")
        self.verticalLayout_5.addWidget(self.Dashboard_btn)
        self.Notices_btn = QtWidgets.QPushButton(self.menu_hcont)
        self.Notices_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Notices_btn.setIcon(icon1)
        self.Notices_btn.setFlat(True)
        self.Notices_btn.setObjectName("Notices_btn")
        self.verticalLayout_5.addWidget(self.Notices_btn)
        self.Admin_btn = QtWidgets.QPushButton(self.menu_hcont)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/admin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Admin_btn.setIcon(icon2)
        self.Admin_btn.setFlat(True)
        self.Admin_btn.setObjectName("Admin_btn")
        self.verticalLayout_5.addWidget(self.Admin_btn)
        self.verticalLayout_4.addWidget(self.menu_hcont)
        self.menu_line1 = QtWidgets.QFrame(self.main_left_hcont)
        self.menu_line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.menu_line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.menu_line1.setObjectName("menu_line1")
        self.verticalLayout_4.addWidget(self.menu_line1)
        self.help_hcont = QtWidgets.QWidget(self.main_left_hcont)
        self.help_hcont.setObjectName("help_hcont")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.help_hcont)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.help_label = QtWidgets.QLabel(self.help_hcont)
        self.help_label.setObjectName("help_label")
        self.verticalLayout_7.addWidget(self.help_label)
        self.help1_btn = QtWidgets.QPushButton(self.help_hcont)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/care.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help1_btn.setIcon(icon3)
        self.help1_btn.setFlat(True)
        self.help1_btn.setObjectName("help1_btn")
        self.verticalLayout_7.addWidget(self.help1_btn)
        self.help2_btn = QtWidgets.QPushButton(self.help_hcont)
        self.help2_btn.setIcon(icon3)
        self.help2_btn.setFlat(True)
        self.help2_btn.setObjectName("help2_btn")
        self.verticalLayout_7.addWidget(self.help2_btn)
        self.help3_btn = QtWidgets.QPushButton(self.help_hcont)
        self.help3_btn.setIcon(icon3)
        self.help3_btn.setFlat(True)
        self.help3_btn.setObjectName("help3_btn")
        self.verticalLayout_7.addWidget(self.help3_btn)
        self.verticalLayout_4.addWidget(self.help_hcont)
        self.menu_line2 = QtWidgets.QFrame(self.main_left_hcont)
        self.menu_line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.menu_line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.menu_line2.setObjectName("menu_line2")
        self.verticalLayout_4.addWidget(self.menu_line2)
        self.user_hcont = QtWidgets.QWidget(self.main_left_hcont)
        self.user_hcont.setObjectName("user_hcont")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.user_hcont)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.user_label = QtWidgets.QLabel(self.user_hcont)
        self.user_label.setObjectName("user_label")
        self.verticalLayout_6.addWidget(self.user_label)
        self.logout_btn = QtWidgets.QPushButton(self.user_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logout_btn.sizePolicy().hasHeightForWidth())
        self.logout_btn.setSizePolicy(sizePolicy)
        self.logout_btn.setMinimumSize(QtCore.QSize(92, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/power-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn.setIcon(icon4)
        self.logout_btn.setFlat(True)
        self.logout_btn.setObjectName("logout_btn")
        self.verticalLayout_6.addWidget(self.logout_btn, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.user_hcont)
        self.horizontalLayout.addWidget(self.main_left_hcont)
        self.vline1 = QtWidgets.QFrame(self.main_vcont)
        self.vline1.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline1.setObjectName("vline1")
        self.horizontalLayout.addWidget(self.vline1)
        self.form_place_hold_vcont = QtWidgets.QFrame(self.main_vcont)
        self.form_place_hold_vcont.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.form_place_hold_vcont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.form_place_hold_vcont.setObjectName("form_place_hold_vcont")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.form_place_hold_vcont)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.form_place_hold_vcont)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.page1_holder = QtWidgets.QWidget(self.page)
        self.page1_holder.setObjectName("page1_holder")
        self.horizontalLayout_3.addWidget(self.page1_holder)


        self.stackedWidget.addWidget(self.page)

        
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.page2_holder = QtWidgets.QWidget(self.page_2)
        self.page2_holder.setObjectName("page2_holder")
        self.horizontalLayout_4.addWidget(self.page2_holder)
        self.stackedWidget.addWidget(self.page_2)

        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.horizontalLayout_page3 = QtWidgets.QHBoxLayout(self.page3)
        self.horizontalLayout_page3.setObjectName("horizontalLayout_page3")
        self.stackedWidget.addWidget(self.page3)
        self.page3_holder = QtWidgets.QWidget(self.page)
        self.page3_holder.setObjectName("page1_holder")
        self.horizontalLayout_page3.addWidget(self.page3_holder)





        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.form_place_hold_vcont)


        self.vline2 = QtWidgets.QFrame(self.main_vcont)
        self.vline2.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline2.setObjectName("vline2")
        self.horizontalLayout.addWidget(self.vline2)
        self.main_right_hcont = QtWidgets.QWidget(self.main_vcont)
        self.main_right_hcont.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_right_hcont.sizePolicy().hasHeightForWidth())
        self.main_right_hcont.setSizePolicy(sizePolicy)
        self.main_right_hcont.setMinimumSize(QtCore.QSize(250, 0))
        self.main_right_hcont.setObjectName("main_right_hcont")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_right_hcont)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.main_right_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.main_right_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 200))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 233, 434))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 30))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13, 0, QtCore.Qt.AlignTop)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.horizontalLayout.addWidget(self.main_right_hcont)
        self.verticalLayout.addWidget(self.main_vcont)
        MainWindow.setCentralWidget(self.Most_outer_hcont)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        form1_widget(self)#step1 send complt self
        form2_widget(self)
        self.Dashboard_btn.clicked.connect(lambda: self.go_to_dash())

        
    def go_to_dash(self):
        DashBoard(self)
        self.stackedWidget.setCurrentIndex(2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header_title.setText(_translate("MainWindow", "A P Shah Institude Of Technology"))
        self.head_btn.setText(_translate("MainWindow", "Dashboard"))
        self.head_logout.setText(_translate("MainWindow", "Logout"))
        self.head_drop.setPlaceholderText(_translate("MainWindow", "HELP DESK"))
        self.head_drop.setItemText(0, _translate("MainWindow", "HELP DESK"))
        self.head_drop.setItemText(1, _translate("MainWindow", "HOD"))
        self.head_drop.setItemText(2, _translate("MainWindow", "help 1"))
        self.head_drop.setItemText(3, _translate("MainWindow", "help 2"))
        self.head_drop.setItemText(4, _translate("MainWindow", "help 3"))
        self.system_label.setText(_translate("MainWindow", "System:"))
        self.Dashboard_btn.setText(_translate("MainWindow", "DashBoard"))
        self.Notices_btn.setText(_translate("MainWindow", "Notices"))
        self.Admin_btn.setText(_translate("MainWindow", "Admin Panel"))
        self.help_label.setText(_translate("MainWindow", "Help:"))
        self.help1_btn.setText(_translate("MainWindow", "Help Center 1"))
        self.help2_btn.setText(_translate("MainWindow", "Help Center 2"))
        self.help3_btn.setText(_translate("MainWindow", "Help Center 3"))
        self.user_label.setText(_translate("MainWindow", "User:"))
        self.logout_btn.setText(_translate("MainWindow", "Logout"))
        self.label_3.setText(_translate("MainWindow", "! News Feed !"))
        self.label_13.setText(_translate("MainWindow", "Admission Started for Year 2022!"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(Form)
    Form.show()
    
    sys.exit(app.exec_())