# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'message.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt 
from PyQt5.QtGui import QTextCursor , QTextBlockFormat , QFont
from PyQt5.QtGui import QColor


class Ui_MessageBox(object):
    def __init__(self, MessageBox): #step 2 init
        self.setupUi( MessageBox )

    def setupUi(self, Obj):
        MessageBox = Obj.page6_holder #step 3 set page #step 4 remove the hoz from main temp
        MessageBox.setObjectName("MessageBox")
        MessageBox.resize(400, 304)
        self.verticalLayout = QtWidgets.QVBoxLayout(MessageBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MessageBoxFloat = QtWidgets.QDockWidget(MessageBox)
        # self.MessageBoxFloat.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable)
        self.MessageBoxFloat.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.MessageBoxFloat.setObjectName("MessageBoxFloat")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.messageTextBox = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.messageTextBox.setObjectName("messageTextBox")
        self.verticalLayout_2.addWidget(self.messageTextBox)
        self.chat_widget = QtWidgets.QWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_widget.sizePolicy().hasHeightForWidth())
        self.chat_widget.setSizePolicy(sizePolicy)
        self.chat_widget.setObjectName("chat_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.chat_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chat_input = QtWidgets.QLineEdit(self.chat_widget)
        self.chat_input.setObjectName("chat_input")
        self.horizontalLayout.addWidget(self.chat_input)
        self.chat_submit = QtWidgets.QPushButton(self.chat_widget)
        self.chat_submit.setObjectName("chat_submit")
        self.horizontalLayout.addWidget(self.chat_submit)
        self.verticalLayout_2.addWidget(self.chat_widget)
        self.MessageBoxFloat.setWidget(self.dockWidgetContents)
        self.verticalLayout.addWidget(self.MessageBoxFloat)

        self.retranslateUi(MessageBox)
        

        self.messageTextBox.setTextBackgroundColor(QColor('#66FFE6'))
        self.messageTextBox.append("textFormatted")

        self.messageTextBox.setTextBackgroundColor(QColor('#66B3FF'))
        self.messageTextBox.append("textFormatted")

        self.messageTextBox.setTextBackgroundColor(QColor('#66FFE6'))
        self.messageTextBox.append("textFormatted")

        self.messageTextBox.setTextBackgroundColor(QColor('#66B3FF'))
        self.chat_submit.clicked.connect(lambda: self.messageTextBox.append(self.chat_input.text()))

        self.MessageBoxFloat.visibilityChanged.connect(lambda: print(True))
        QtCore.QMetaObject.connectSlotsByName(MessageBox)

    def retranslateUi(self, MessageBox):
        _translate = QtCore.QCoreApplication.translate
        MessageBox.setWindowTitle(_translate("MessageBox", "Form"))
        self.messageTextBox.setHtml(_translate("MessageBox", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Fira Sans Semi-Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:10px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.chat_submit.setText(_translate("MessageBox", "Submit"))

        self.messageTextBox.setReadOnly(True)
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_MessageBox()
    ui.setupUi(Form)
    Form.show()
    
    sys.exit(app.exec_())