# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrationForm_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog 
import MysqlConn
import os

class Ui_Form(object):
    def __init__(self, Form): #step 2 init
        self.setupUi( Form )

    def setupUi(self, Obj):
        Form = Obj.page2_holder #step 3 set page #step 4 remove the hoz from main temp

        Form.setObjectName("Form")
        Form.resize(970, 841)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_middle_scroll_area = QtWidgets.QScrollArea(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_middle_scroll_area.sizePolicy().hasHeightForWidth())
        self.main_middle_scroll_area.setSizePolicy(sizePolicy)
        self.main_middle_scroll_area.setMinimumSize(QtCore.QSize(0, 100))
        self.main_middle_scroll_area.setStyleSheet("\n"
"\n"
"QLabel{\n"
"    font-family: \"DejaVu Serif\" ;\n"
"\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton{\n"
"height: 30px;\n"
"\n"
"}\n"
"QDateEdit{\n"
"height: 30px;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"height: 30px;\n"
"\n"
"}\n"
"QComboBox{\n"
"height: 30px;\n"
"\n"
"}\n"
"")
        self.main_middle_scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_middle_scroll_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.main_middle_scroll_area.setWidgetResizable(True)
        self.main_middle_scroll_area.setObjectName("main_middle_scroll_area")
        self.middle_scroll_area_vcont_3 = QtWidgets.QWidget()
        self.middle_scroll_area_vcont_3.setGeometry(QtCore.QRect(0, 0, 952, 823))
        self.middle_scroll_area_vcont_3.setObjectName("middle_scroll_area_vcont_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.middle_scroll_area_vcont_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.personal_info_header_3 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personal_info_header_3.sizePolicy().hasHeightForWidth())
        self.personal_info_header_3.setSizePolicy(sizePolicy)
        self.personal_info_header_3.setMinimumSize(QtCore.QSize(0, 20))
        self.personal_info_header_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.personal_info_header_3.setStyleSheet("*{font-family:  \"DejaVu Math TeX Gyre\";\n"
"    font-size:20px\n"
"}")
        self.personal_info_header_3.setObjectName("personal_info_header_3")
        self.verticalLayout_10.addWidget(self.personal_info_header_3, 0, QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(self.middle_scroll_area_vcont_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_10.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.form_gridCont_3 = QtWidgets.QGridLayout()
        self.form_gridCont_3.setObjectName("form_gridCont_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.form_gridCont_3.addWidget(self.lineEdit_6, 9, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_12.setObjectName("label_12")
        self.form_gridCont_3.addWidget(self.label_12, 16, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.middle_scroll_area_vcont_3)
        self.pushButton.setObjectName("pushButton")
        self.form_gridCont_3.addWidget(self.pushButton, 18, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.middle_scroll_area_vcont_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.form_gridCont_3.addWidget(self.pushButton_3, 14, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.middle_scroll_area_vcont_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.form_gridCont_3.addWidget(self.line_2, 5, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.middle_scroll_area_vcont_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.form_gridCont_3.addWidget(self.line_4, 5, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.middle_scroll_area_vcont_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.form_gridCont_3.addWidget(self.line_3, 5, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.middle_scroll_area_vcont_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.form_gridCont_3.addWidget(self.comboBox_2, 1, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_5.setObjectName("label_5")
        self.form_gridCont_3.addWidget(self.label_5, 7, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.middle_scroll_area_vcont_3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.form_gridCont_3.addWidget(self.line_7, 11, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.form_gridCont_3.addWidget(self.lineEdit_9, 14, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.form_gridCont_3.addWidget(self.lineEdit_10, 15, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.form_gridCont_3.addWidget(self.comboBox, 0, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_13.setObjectName("label_13")
        self.form_gridCont_3.addWidget(self.label_13, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label.setObjectName("label")
        self.form_gridCont_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_9.setObjectName("label_9")
        self.form_gridCont_3.addWidget(self.label_9, 13, 0, 1, 1)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.middle_scroll_area_vcont_3)
        self.dateEdit_3.setCalendarPopup(True)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.form_gridCont_3.addWidget(self.dateEdit_3, 10, 2, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.middle_scroll_area_vcont_3)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.form_gridCont_3.addWidget(self.dateEdit, 8, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.middle_scroll_area_vcont_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.form_gridCont_3.addWidget(self.line_6, 11, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.form_gridCont_3.addItem(spacerItem, 12, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_3.setObjectName("label_3")
        self.form_gridCont_3.addWidget(self.label_3, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_5 = QtWidgets.QPushButton(self.middle_scroll_area_vcont_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.form_gridCont_3.addWidget(self.pushButton_5, 16, 2, 1, 1)
        self.dob_setter_3 = QtWidgets.QDateEdit(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dob_setter_3.sizePolicy().hasHeightForWidth())
        self.dob_setter_3.setSizePolicy(sizePolicy)
        self.dob_setter_3.setProperty("showGroupSeparator", False)
        self.dob_setter_3.setCalendarPopup(True)
        self.dob_setter_3.setTimeSpec(QtCore.Qt.LocalTime)
        self.dob_setter_3.setObjectName("dob_setter_3")
        self.form_gridCont_3.addWidget(self.dob_setter_3, 7, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_8.setObjectName("label_8")
        self.form_gridCont_3.addWidget(self.label_8, 10, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_11.setObjectName("label_11")
        self.form_gridCont_3.addWidget(self.label_11, 15, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_6.setObjectName("label_6")
        self.form_gridCont_3.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_2.setObjectName("label_2")
        self.form_gridCont_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.middle_scroll_area_vcont_3)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.form_gridCont_3.addWidget(self.dateEdit_2, 9, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.middle_scroll_area_vcont_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.form_gridCont_3.addWidget(self.pushButton_2, 13, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.form_gridCont_3.addWidget(self.lineEdit_11, 16, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_4.setObjectName("label_4")
        self.form_gridCont_3.addWidget(self.label_4, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.line_5 = QtWidgets.QFrame(self.middle_scroll_area_vcont_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.form_gridCont_3.addWidget(self.line_5, 11, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.form_gridCont_3.addWidget(self.lineEdit_4, 7, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_10.setObjectName("label_10")
        self.form_gridCont_3.addWidget(self.label_10, 14, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.form_gridCont_3.addWidget(self.lineEdit_5, 8, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        self.label_7.setObjectName("label_7")
        self.form_gridCont_3.addWidget(self.label_7, 9, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.form_gridCont_3.addWidget(self.lineEdit_7, 10, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.form_gridCont_3.addWidget(self.lineEdit_8, 13, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.form_gridCont_3.addItem(spacerItem1, 17, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.middle_scroll_area_vcont_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.form_gridCont_3.addWidget(self.pushButton_4, 15, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.form_gridCont_3.addItem(spacerItem2, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.form_gridCont_3)
        self.image_profile_3 = QtWidgets.QLabel(self.middle_scroll_area_vcont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_profile_3.sizePolicy().hasHeightForWidth())
        self.image_profile_3.setSizePolicy(sizePolicy)
        self.image_profile_3.setMaximumSize(QtCore.QSize(100, 100))
        self.image_profile_3.setAutoFillBackground(False)
        self.image_profile_3.setStyleSheet("")
        self.image_profile_3.setText("")
        self.image_profile_3.setPixmap(QtGui.QPixmap("../../../../../../../Pictures/Wallpapers/wallhaven-g821oe.jpg"))
        self.image_profile_3.setScaledContents(True)
        self.image_profile_3.setObjectName("image_profile_3")
        self.verticalLayout.addWidget(self.image_profile_3)
        self.verticalLayout_10.addLayout(self.verticalLayout)
        self.main_middle_scroll_area.setWidget(self.middle_scroll_area_vcont_3)
        self.horizontalLayout.addWidget(self.main_middle_scroll_area)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(lambda: self.UploadForm(Obj))
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton_2.clicked.connect(lambda: self.FileUpload('ssc'))
        self.pushButton_3.clicked.connect(lambda: self.FileUpload('hsc'))
        self.pushButton_4.clicked.connect(lambda: self.FileUpload('mhcet'))
        self.pushButton_5.clicked.connect(lambda: self.FileUpload('jee'))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.personal_info_header_3.setText(_translate("Form", "Registration Form"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "-/10"))
        self.label_12.setText(_translate("Form", "JEE Marksheet"))
        self.pushButton.setText(_translate("Form", "Submit"))
        self.pushButton_3.setText(_translate("Form", "Select File"))
        self.comboBox_2.setItemText(0, _translate("Form", "----"))
        self.comboBox_2.setItemText(1, _translate("Form", "IT"))
        self.comboBox_2.setItemText(2, _translate("Form", "Tech"))
        self.comboBox_2.setItemText(3, _translate("Form", "Civil"))
        self.comboBox_2.setItemText(4, _translate("Form", "Mech"))
        self.label_5.setText(_translate("Form", "SSC Percentage"))
        self.lineEdit_9.setPlaceholderText(_translate("Form", "No file Selected"))
        self.lineEdit_10.setPlaceholderText(_translate("Form", "No file Selected"))
        self.comboBox.setItemText(0, _translate("Form", "IT"))
        self.comboBox.setItemText(1, _translate("Form", "CS"))
        self.comboBox.setItemText(2, _translate("Form", "Mech"))
        self.comboBox.setItemText(3, _translate("Form", "Civil"))
        self.label_13.setText(_translate("Form", "Date of passing"))
        self.label.setText(_translate("Form", "Branch"))
        self.label_9.setText(_translate("Form", "SSC Marksheet"))
        self.label_3.setText(_translate("Form", "Exams"))
        self.pushButton_5.setText(_translate("Form", "Select File"))
        self.dob_setter_3.setDisplayFormat(_translate("Form", "d/M/yy"))
        self.label_8.setText(_translate("Form", "JEE Percentile"))
        self.label_11.setText(_translate("Form", "MHT-CET Marksheet"))
        self.label_6.setText(_translate("Form", "HSC Percentage"))
        self.label_2.setText(_translate("Form", "Preferred-Branch (Optional)"))
        self.pushButton_2.setText(_translate("Form", "Select File"))
        self.lineEdit_11.setPlaceholderText(_translate("Form", "No file Selected"))
        self.label_4.setText(_translate("Form", "Percentage"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "-/100"))
        self.label_10.setText(_translate("Form", "HSC Marksheet"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "-/100"))
        self.label_7.setText(_translate("Form", "MHT-CET Percentile"))
        self.lineEdit_7.setPlaceholderText(_translate("Form", "-/10"))
        self.lineEdit_8.setPlaceholderText(_translate("Form", "No file Selected"))
        self.pushButton_4.setText(_translate("Form", "Select File"))

    def FileUpload(self, type):
        fname = QFileDialog.getOpenFileName(None, "Open File", "/home/chirag/", " Document or Images (*.png *.jpg *.bmp *.pdf)"  )
        #split_tup = os.path.splitext(fname[0])
        # Output filename to screen
        if type == "ssc" and len(fname[0]) != 0:
            self.lineEdit_8.setText(fname[0])
        elif type == "hsc"  and len(fname[0]) != 0:
            self.lineEdit_9.setText(fname[0])
        elif type == "mhcet"  and len(fname[0]) != 0:
            self.lineEdit_10.setText(fname[0])
        elif type == "jee"  and len(fname[0]) != 0:
            self.lineEdit_11.setText(fname[0])

    def UploadForm(self, Obj):
        sql = " INSERT INTO `Academic_Details` ( `Std_ID`, `Branch`, `Branch_Preferred`, `SSC`, `HSC`, `mhtcet`, `jee`, `ssc_date`, `hsc_date`, `mhcet_date`, `jee_date`,  `ssc_file`, `hsc_file`, `mhcet_file`, `jee_file`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)  "
        val = (
            MysqlConn.RowCount() + 1,
            self.comboBox.currentText(),
            self.comboBox_2.currentText(),

            self.lineEdit_4.text(),
            self.lineEdit_5.text(),
            self.lineEdit_6.text(),
            self.lineEdit_7.text(),

            self.dob_setter_3.text(),
            self.dateEdit.text(),
            self.dateEdit_2.text(),
            self.dateEdit_3.text(),

            self.lineEdit_8.text(),
            self.lineEdit_9.text(),
            self.lineEdit_10.text(),
            self.lineEdit_11.text(),
                )
        if MysqlConn.UploadForm(sql, val, False) == True: 
            Obj.stackedWidget.setCurrentIndex(6)
        else: MysqlConn.AlertPop("Wrong Or Empty Data!")