
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_panel_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5 import QtCore, QtGui, QtWidgets 
from components.personalinfo_form_widget import Ui_Form
from components.registrationForm_widget import Ui_Form as Ui_Form2
from components.payment_layout import Ui_Payment as Ui_Form3
from components.dashboard_widget import Ui_Form as DashBoard
from components.admin_panel_widget import Ui_Form as AdminPanel
from components.notice_widget import Ui_Form as NoticePanel
from components.message import Ui_MessageBox as MessagePanel
from PyQt5.QtCore import QSettings


class Ui_MainWindow(object):
    signal_notice = QtCore.pyqtSignal()
    settings = QSettings("MySoft", "Star Runner")
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1221, 555)
        MainWindow.setMinimumSize(QtCore.QSize(1000,620))
        self.Most_outer_hcont = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Most_outer_hcont.sizePolicy().hasHeightForWidth())
        self.Most_outer_hcont.setSizePolicy(sizePolicy)
        self.Most_outer_hcont.setObjectName("Most_outer_hcont")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Most_outer_hcont)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header_Vcont = QtWidgets.QHBoxLayout()
        self.Header_Vcont.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.Header_Vcont.setSpacing(10)
        self.Header_Vcont.setObjectName("Header_Vcont")
        self.head_logo = QtWidgets.QLabel(self.Most_outer_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head_logo.sizePolicy().hasHeightForWidth())
        self.head_logo.setSizePolicy(sizePolicy)
        self.head_logo.setMinimumSize(QtCore.QSize(10, 10))
        self.head_logo.setMaximumSize(QtCore.QSize(50, 50))
        self.head_logo.setText("")
        self.head_logo.setPixmap(QtGui.QPixmap("icons/apshah_logo.png"))

        self.head_logo.setScaledContents(True)
        self.head_logo.setObjectName("head_logo")
        self.Header_Vcont.addWidget(self.head_logo)
        self.header_title = QtWidgets.QLabel(self.Most_outer_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_title.sizePolicy().hasHeightForWidth())
        self.header_title.setSizePolicy(sizePolicy)
        self.header_title.setMinimumSize(QtCore.QSize(10, 10))
        self.header_title.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.header_title.setStyleSheet("*{\n"
"    \n"
"    font: 75 15pt \"DejaVu Serif\";\n"
"}\n"
"")
        self.header_title.setObjectName("header_title")
        self.Header_Vcont.addWidget(self.header_title)
        self.head_btn = QtWidgets.QLabel(self.Most_outer_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head_btn.sizePolicy().hasHeightForWidth())
        self.head_btn.setSizePolicy(sizePolicy)
        self.head_btn.setMinimumSize(QtCore.QSize(10, 0))
        self.head_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.head_btn.setStyleSheet("")
        self.head_btn.setObjectName("head_btn")
        self.Header_Vcont.addWidget(self.head_btn)
        self.head_logout = QtWidgets.QLabel(self.Most_outer_hcont)
        self.head_btn.setPixmap(QtGui.QPixmap("icons/sun.png"))
        self.head_btn.setScaledContents(True)
        self.head_btn.setFixedSize(20, 20)
        #self.head_btn.resize(pixmap.width(), pixmap.height())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head_logout.sizePolicy().hasHeightForWidth())
        self.head_logout.setSizePolicy(sizePolicy)
        self.head_logout.setMinimumSize(QtCore.QSize(10, 0))
        self.head_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.head_logout.setObjectName("head_logout")
        self.Header_Vcont.addWidget(self.head_logout)
        self.head_drop = QtWidgets.QComboBox(self.Most_outer_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head_drop.sizePolicy().hasHeightForWidth())
        self.head_drop.setSizePolicy(sizePolicy)
        self.head_drop.setMinimumSize(QtCore.QSize(10, 0))
        self.head_drop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.head_drop.setCurrentText("")
        self.head_drop.setFrame(True)
        self.head_drop.setObjectName("head_drop")
        self.head_drop.addItem("")
        self.head_drop.addItem("")
        self.head_drop.setItemText(2, "")
        self.Header_Vcont.addWidget(self.head_drop)
        self.verticalLayout.addLayout(self.Header_Vcont)
        self.head_line = QtWidgets.QFrame(self.Most_outer_hcont)
        self.head_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.head_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.head_line.setObjectName("head_line")
        self.verticalLayout.addWidget(self.head_line)
        self.main_vcont = QtWidgets.QWidget(self.Most_outer_hcont)
        self.main_vcont.setObjectName("main_vcont")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_vcont)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_left_hcont = QtWidgets.QWidget(self.main_vcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_left_hcont.sizePolicy().hasHeightForWidth())
        self.main_left_hcont.setSizePolicy(sizePolicy)
        self.main_left_hcont.setMinimumSize(QtCore.QSize(80, 0))
        self.main_left_hcont.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.main_left_hcont.setStyleSheet("QPushButton{\n"
"    text-align: left;\n"
"    font: 75 italic 10pt \"DejaVu Serif\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font-weight: bold\n"
"    \n"
"}\n"
"\n"
"QPushButton{\n"
"\n"
"height:30px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"padding: 10px"
"}\n"
"*{\n"
"margin-left: 15pt;\n"
"margin-right: 15pt;\n"
"min-width: 80px\n"
"}")
        self.main_left_hcont.setObjectName("main_left_hcont")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_left_hcont)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.menu_hcont = QtWidgets.QWidget(self.main_left_hcont)
        self.menu_hcont.setMinimumSize(QtCore.QSize(80, 0))
        self.menu_hcont.setStyleSheet("")
        self.menu_hcont.setObjectName("menu_hcont")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.menu_hcont)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.system_label = QtWidgets.QLabel(self.menu_hcont)
        self.system_label.setObjectName("system_label")
        self.verticalLayout_5.addWidget(self.system_label )
        self.Dashboard_btn = QtWidgets.QPushButton(self.menu_hcont)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Dashboard_btn.setIcon(icon)
        self.Dashboard_btn.setFlat(True)
        self.Dashboard_btn.setObjectName("Dashboard_btn")
        self.verticalLayout_5.addWidget(self.Dashboard_btn)
        self.Notices_btn = QtWidgets.QPushButton(self.menu_hcont)
        self.Notices_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Notices_btn.setIcon(icon1)
        self.Notices_btn.setFlat(True)
        self.Notices_btn.setObjectName("Notices_btn")
        self.verticalLayout_5.addWidget(self.Notices_btn)
        self.Admin_btn = QtWidgets.QPushButton(self.menu_hcont)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/admin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Admin_btn.setIcon(icon2)
        self.Admin_btn.setFlat(True)
        self.Admin_btn.setObjectName("Admin_btn")
        self.verticalLayout_5.addWidget(self.Admin_btn)
        self.verticalLayout_4.addWidget(self.menu_hcont)
        self.menu_line1 = QtWidgets.QFrame(self.main_left_hcont)
        self.menu_line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.menu_line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.menu_line1.setObjectName("menu_line1")
        self.verticalLayout_4.addWidget(self.menu_line1)
        self.help_hcont = QtWidgets.QWidget(self.main_left_hcont)
        self.help_hcont.setObjectName("help_hcont")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.help_hcont)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.help_label = QtWidgets.QLabel(self.help_hcont)
        self.help_label.setObjectName("help_label")
        self.verticalLayout_7.addWidget(self.help_label)
        self.help1_btn = QtWidgets.QPushButton(self.help_hcont)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/care.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help1_btn.setIcon(icon3)
        self.help1_btn.setFlat(True)
        self.help1_btn.setObjectName("help1_btn")
        self.verticalLayout_7.addWidget(self.help1_btn)
        self.verticalLayout_4.addWidget(self.help_hcont)
        self.menu_line2 = QtWidgets.QFrame(self.main_left_hcont)
        self.menu_line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.menu_line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.menu_line2.setObjectName("menu_line2")
        self.verticalLayout_4.addWidget(self.menu_line2)
        self.user_hcont = QtWidgets.QWidget(self.main_left_hcont)
        self.user_hcont.setObjectName("user_hcont")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.user_hcont)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.user_label = QtWidgets.QLabel(self.user_hcont)
        self.user_label.setObjectName("user_label")
        self.verticalLayout_6.addWidget(self.user_label)
        self.logout_btn = QtWidgets.QPushButton(self.user_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logout_btn.sizePolicy().hasHeightForWidth())
        self.logout_btn.setSizePolicy(sizePolicy)
        self.logout_btn.setMinimumSize(QtCore.QSize(92, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/power-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn.setIcon(icon4)
        self.logout_btn.setFlat(True)
        self.logout_btn.setObjectName("logout_btn")
        self.verticalLayout_6.addWidget(self.logout_btn, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.user_hcont)
        self.horizontalLayout.addWidget(self.main_left_hcont ,0, QtCore.Qt.AlignTop)
        self.vline1 = QtWidgets.QFrame(self.main_vcont)
        self.vline1.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline1.setObjectName("vline1")
        self.horizontalLayout.addWidget(self.vline1)
        self.form_place_hold_vcont = QtWidgets.QFrame(self.main_vcont)
        self.form_place_hold_vcont.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.form_place_hold_vcont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.form_place_hold_vcont.setObjectName("form_place_hold_vcont")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.form_place_hold_vcont)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.form_place_hold_vcont)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.page1_holder = QtWidgets.QWidget(self.page)
        self.page1_holder.setObjectName("page1_holder")
        self.horizontalLayout_3.addWidget(self.page1_holder)


        self.stackedWidget.addWidget(self.page)

        
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.page2_holder = QtWidgets.QWidget(self.page_2)
        self.page2_holder.setObjectName("page2_holder")
        self.horizontalLayout_4.addWidget(self.page2_holder)
        self.stackedWidget.addWidget(self.page_2)

        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.horizontalLayout_page3 = QtWidgets.QHBoxLayout(self.page3)
        self.horizontalLayout_page3.setObjectName("horizontalLayout_page3")
        self.stackedWidget.addWidget(self.page3)
        self.page3_holder = QtWidgets.QWidget(self.page3)
        self.page3_holder.setObjectName("page1_holder")
        self.horizontalLayout_page3.addWidget(self.page3_holder)

        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.horizontalLayout_page4 = QtWidgets.QHBoxLayout(self.page4)
        self.horizontalLayout_page4.setObjectName("horizontalLayout_page4")
        self.stackedWidget.addWidget(self.page4)
        self.page4_holder = QtWidgets.QWidget(self.page4)
        self.page4_holder.setObjectName("page4_holder")
        self.horizontalLayout_page4.addWidget(self.page4_holder)

        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.horizontalLayout_page5 = QtWidgets.QHBoxLayout(self.page5)
        self.horizontalLayout_page5.setObjectName("horizontalLayout_page5")
        self.stackedWidget.addWidget(self.page5)
        self.page5_holder = QtWidgets.QWidget(self.page5)
        self.page5_holder.setObjectName("page5_holder")
        self.horizontalLayout_page5.addWidget(self.page5_holder)

        self.page6 = QtWidgets.QWidget()
        self.page6.setObjectName("page6")
        self.horizontalLayout_page6 = QtWidgets.QHBoxLayout(self.page6)
        self.horizontalLayout_page6.setObjectName("horizontalLayout_page6")
        self.stackedWidget.addWidget(self.page6)
        self.page6_holder = QtWidgets.QWidget(self.page6)
        self.page6_holder.setObjectName("page6_holder")
        self.horizontalLayout_page6.addWidget(self.page6_holder)


        self.page7 = QtWidgets.QWidget()
        self.page7.setObjectName("page7")
        self.horizontalLayout_page7 = QtWidgets.QHBoxLayout(self.page7)
        self.horizontalLayout_page7.setObjectName("horizontalLayout_page7")
        self.stackedWidget.addWidget(self.page7)
        self.page7_holder = QtWidgets.QWidget(self.page7)
        self.page7_holder.setObjectName("page7_holder")
        self.horizontalLayout_page7.addWidget(self.page7_holder)


        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.form_place_hold_vcont)


        self.vline2 = QtWidgets.QFrame(self.main_vcont)
        self.vline2.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline2.setObjectName("vline2")
        self.horizontalLayout.addWidget(self.vline2)
        self.main_right_hcont = QtWidgets.QWidget(self.main_vcont)
        self.main_right_hcont.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_right_hcont.sizePolicy().hasHeightForWidth())
        self.main_right_hcont.setSizePolicy(sizePolicy)
        self.main_right_hcont.setMinimumSize(QtCore.QSize(250, 0))
        self.main_right_hcont.setObjectName("main_right_hcont")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_right_hcont)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.main_right_hcont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)

        self.MainTextEdit = QtWidgets.QTextEdit(self.main_right_hcont)
        self.MainTextEdit.setObjectName("MainTextEdit")
        self.MainTextEdit.setReadOnly(True)

        self.verticalLayout_2.addWidget(self.MainTextEdit)

        self.horizontalLayout.addWidget(self.main_right_hcont)
        self.verticalLayout.addWidget(self.main_vcont)
        MainWindow.setCentralWidget(self.Most_outer_hcont)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # self.settings.setValue('context', 'king')

        self.go_to_dash_and_load_pages()
        self.Dashboard_btn.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        self.Notices_btn.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(4))
        self.Admin_btn.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3))
        self.help1_btn.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(5))

    #     self.logout_btn.clicked.connect(lambda: self.signal_notice.emit())
    # def changeForm(self):
    #     a = self.stackedWidget.currentIndex()
    #     b = [0,1,6]
    #     if a in b: 
    #         index = b.index(a)
    #         self.stackedWidget.setCurrentIndex(b[(index - 1)%3])
    #         MysqlConn.Backward()
    #         print(
    #             MysqlConn.sql_arr," -- ",
    #             MysqlConn.val_arr, "  -- ",
    #             MysqlConn.iterator
    #         )
    def go_to_dash_and_load_pages(self):
        Ui_Form(self)#0
        Ui_Form2(self)#1
        DashBoard(self)#2
        AdminPanel(self)#3
        NoticePanel(self)#4
        MessagePanel(self)#5
        Ui_Form3(self)#6
        self.stackedWidget.setCurrentIndex(2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header_title.setText(_translate("MainWindow", "A P Shah Institude Of Technology"))
        # self.head_btn.setText(_translate("MainWindow", "Dashboard"))
        self.head_logout.setText(_translate("MainWindow", "Theme: "))
        self.head_drop.setPlaceholderText(_translate("MainWindow", "HELP DESK"))
        self.head_drop.setItemText(0, _translate("MainWindow", "Light"))
        self.head_drop.setItemText(1, _translate("MainWindow", "Dark"))
        self.system_label.setText(_translate("MainWindow", "System:"))
        self.Dashboard_btn.setText(_translate("MainWindow", "DashBoard"))
        self.Notices_btn.setText(_translate("MainWindow", "Notices"))
        self.Admin_btn.setText(_translate("MainWindow", "Admin Panel"))
        self.help_label.setText(_translate("MainWindow", "Help:"))
        self.help1_btn.setText(_translate("MainWindow", "Help Center 1"))
        self.user_label.setText(_translate("MainWindow", "User:"))
        self.logout_btn.setText(_translate("MainWindow", "Logout"))
        self.label_3.setText(_translate("MainWindow", "! News Feed !"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(Form)
    Form.show()
    
    sys.exit(app.exec_())
